### PR TITLE
Fulltext downloading and viewing

### PR DESCRIPTION
**Pull request by blahah**
This PR depends on #7 

- [x] data source selection backend
- [x] paper fulltext XML downloading from a single HTTP source (for now)
- [x] visual feedback about download status
- [x] read downloaded XML in eLife lens
- [x] fix up the eupmc lens converter
- [x] reduce the metadata set to only the full OA papers (~1.2 million) for the initial release
  - transferred to #14

### CODE REVIEW

**Comment by blahah** [comment]
the yellow bar now really denotes whether a paper has been downloaded. It also persists between launches - when a `Paper` is updated with metadata, it checks to see if the corresponding file exists, and if so displays the bar.
screenshot 2016-04-05 14 47 49

**Comment by blahah** [comment]
Sometimes a fulltext version of the paper can't be found for whatever reason - in which case we show a rose bar to indicate failure. This doesn't persist between launches.

screenshot 2016-04-05 14 49 19

**Comment by blahah** [comment]
I chose the rose colour using [colorhexa's profile for the yellow](http://www.colorhexa.com/caac4d) - I went with the tetradic red.

screenshot 2016-04-05 14 51 34

**Comment by blahah** [comment]
jbq65pomju

**Comment by karissa** [comment]
WOW you're awesome!!!

**Comment by blahah** [comment]
this is now ready to review :)

**Comment by karissa** [comment]
I think you should merge this

**Pull request merged**
