### PR TITLE
Contribution Guidelines and Code of Conduct

### PR DESCRIPTION
**Pull request by npch**
I've added drafts of Contribution Guidelines and Code of Conduct.

Some things that should be resolved before these are accepted:
- conduct@codeforscience.com email alias should be set up, forwarding to the Code For Science Team
- agree with Mozilla Science Lab who should be emailed for escalation of reports relating to Code of Conduct
- someone from the Code For Science team should review the documents and see if they agree with them :-)

Some things which could be considered, but aren't necessary for acceptance:
- consider using standard labels (e.g. Easy Pick) in the issues to mark out low hanging fruit for potential contributors

### CODE REVIEW

**Comment by blahah** [comment]
@npch do you know of a source of standard issue label names? I don't think I've seen any kind of standard before.

**Comment by blahah** [comment]
and I forgot to say thanks so much for this! A huge improvement to the repo :)

**Comment by auremoser** [comment]
Love this COC @npch, I checked out your PR and made changes locally but don't have push permissions, so I'll add some suggestions here. 

screen shot 2016-06-02 at 11 21 23 am

Under **Reporting**, feel free to list me as the Mozilla Science arbiter:

>If your report is concerning a member of the Code For Science team, and you do not wish them to see the report, you may escalate your report by sending it directly to the independent arbiter, Mozilla Science Lab. You can email [Aurelia](https://github.com/auremoser) at the Science Lab directly (aurelia@mozillafoundation.org) and she will reach out and handle your case with the unmost professionalism and discretion. If you're not comfortable emailing only Aurelia, you can reach out to the science lab team as a whole: sciencelab@mozillafoundation.org.

Likewise, feel free to change the language if you think an alternate articulation is best.

**Comment by blahah** [comment]
I think @auremoser has made the changes mentioned above in the https://github.com/codeforscience/sciencefair/tree/documentation branch

**Comment by auremoser** [comment]
Yes, sorry @blahah, if I messed that up, I checked out the PR but pushed the changes tithe master documentation branch and not the forked one :/ apparently.

**Comment by blahah** [comment]
@auremoser not at all, that's perfect because when we merge `documentation` into `master` it will mark this PR as merged and close it :)

You have come to a clearing in the repo. There are three items resting on the ground in the clearing:

🏆 🍪 🌵 

A worn scrap of parchment is pinned to the ground in front of the items. it reads:

> You may choose one item to take with you as you continue on your quest.
> Choose wisely - a poor choice may lead to misery, while an apt choice will open the door to great riches.

**Comment by auremoser** [comment]
Wow, well if it's survival we're going for I think [the decision is obvious](http://survivial-training.wonderhowto.com/how-to/eat-extract-water-from-cactus-346549/).

(after only 8 hours of contemplation)

**Comment by blahah** [comment]
@auremoser only 9 months late, but: 🌵

**Comment by blahah** [comment]
At long last, we're ready to merge this! Thanks so much @npch :)

**Pull request merged**
