### PR TITLE
progress bar

### PR DESCRIPTION
**Pull request by freeman-lab**
Adds a simple progress bar for db initialization. Will be connected to dat download progress, bur for now just provides the UI.

initialize

### CODE REVIEW

**Comment by maxogden** [comment]
optional info we can show from dat:

- amount of sources downloading from
- total download speed
- estimated time to completion

**Comment by freeman-lab** [comment]
ah sweet, we'll probably want some of those permanently in the bottom bar (where transfer speed is now), because we'll want them during other downloads too.

maybe this? (where "results" only appears once you start searching)

@Blahah is that the extra info you wanted in the footer? other stuff too?

screen shot 2016-02-29 at 2 48 55 pm

**Comment by Blahah** [comment]
Yes! this is what I was imagining :)

**Comment by blahah** [comment]
All this stuff is now included - your designs were used @freeman-lab but it was implemented as choo views. Will land in v1.

**Pull request closed without merging**
