### PR TITLE
Add a real data source (Europe PubMed Central)

### PR DESCRIPTION
**Pull request by blahah**
This PR adds the first demo dataset - a simple set of metadata from all ~3.5 million full-text articles in Europe PubMed Central.

Fields included:

- `doi`
- `title`
- `authorString` (comma-separated list of authors in `initials lastname` format)
- `year`

Tasks:

- [x] create and share the sqlite database 
  - dat://b57f332de2444ac963bb764f3b4e0b8cf01a42044501e688d0a5f1a2f701ca71
- [x] add a script to grab the database
- [x] use the real data in the app
- [x] fix up the UI to work with the new data nicely
- [x] add simple result paging
- [x] add search stats
- [x] add infinite scrolling (moved to new issue #8)
- [x] highlight search term matches in the result cards (moved to new issue #9)

**Please don't merge until the `WIP` label is removed.**

### CODE REVIEW

**Comment by Blahah** [comment]
Screenshot of current status:

screenshot 2016-03-01 15 46 18

**Comment by Blahah** [comment]
@maxogden thanks - I've got a few more bits to add before it's ready

**Comment by freeman-lab** [comment]
yeah this is looking really good! remind us how big the db is? we might want a script / flag that downloads a much smaller version but with real content for testing?

**Comment by Blahah** [comment]
@freeman-lab it's currently 1.43 GB, and that's only a few fields. Good idea - I'll make a tiny testing set.

**Comment by Blahah** [comment]
This PR is now ready to review @freeman-lab @maxogden. I'm saving infinite scrolling and search term highlighting for future PRs. Fulltext downloading is not implemented, but the fulltext dataset is in place and managed via `dat-manager`. A test database of 10k articles is setup, and is currently set as the db. You can turn off testing to get the full metadata db.

home search screen after data source is loaded
screenshot 2016-03-30 09 38 49

first page of search results
screenshot 2016-03-30 09 39 01

middle page
screenshot 2016-03-30 09 39 10

final page
screenshot 2016-03-30 09 39 18

**Comment by freeman-lab** [comment]
Looks awesome, and runs for me! Merging in, we can keep tweaking from there.

**Pull request merged**
